version: '3.7'
services:
  db:
    image: postgres:16.9
    environment:
      POSTGRES_USER: bors
      POSTGRES_PASSWORD: bors
      POSTGRES_DB: bors
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
